from src.common.enum import BaseEnum


class EventTypeEnum(BaseEnum):
    # Application
    SOURCE_DATA_UPDATED = 'SOURCE_DATA_UPDATED'

    # Triggers
    DELIVERABLES_DUE = 'DELIVERABLES_DUE'
    CLUSTER_TASKS_DUE = 'CLUSTER_TASKS_DUE'
    CLUSTER_TASK_ASSIGNED = 'CLUSTER_TASK_ASSIGNED'
    DELIVERABLE_ASSIGNED = 'DELIVERABLE_ASSIGNED'
    ENTITY_CREATED = 'ENTITY_CREATED'
    ENTITY_MEMBERSHIP_INVITED = 'ENTITY_MEMBERSHIP_INVITED'
    ENTITY_MEMBERSHIP_ACTIVATED = 'ENTITY_MEMBERSHIP_ACTIVATED'
    DELIVERABLE_COMPLETED = 'DELIVERABLE_COMPLETED'
    EXTRACTION_PUBLISHED = 'EXTRACTION_PUBLISHED'
    FIELD_VALUES_UPDATED = 'FIELD_VALUES_UPDATED'
    DOCUMENTS_UPLOADED = 'DOCUMENTS_UPLOADED'
    DOCUMENT_PARSED = 'DOCUMENT_PARSED'
    DOCUMENT_INDEXED = 'DOCUMENT_INDEXED'
    SCHEDULE_TRIGGERED = 'SCHEDULE_TRIGGERED'
    ASSET_ACCOUNT_ADDED = 'ASSET_ACCOUNT_ADDED'
    ASSET_ACCOUNT_ARCHIVED = 'ASSET_ACCOUNT_ARCHIVED'
