"""audit-setup

Revision ID: 533d9fc57bb8
Revises: ee9654a7397f
Create Date: 2023-05-09 23:05:08.121014

"""

import os

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '533d9fc57bb8'
down_revision = 'aba94e302521'
branch_labels = None
depends_on = None


def read_sql_file():
    dir_path = os.path.dirname(os.path.abspath(__file__))
    file_path = os.path.join(dir_path, '00-system-audit.sql')
    with open(file_path, 'r') as file:
        return file.read()


def upgrade() -> None:
    audit_sql = read_sql_file()
    conn = op.get_bind()
    conn.execute(sa.text(audit_sql))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ...
