"""app-audit setup

Revision ID: d71b24224f51
Revises: 6bae295331c0
Create Date: 2023-12-26 14:48:46.780454

"""

import os

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd71b24224f51'
down_revision = 'x3441dqa3kpp'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'auditevent',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('request_id', sa.String(length=50), nullable=True),
        sa.Column('txn_id', sa.BigInteger(), nullable=False),
        sa.Column('breadcrumb', sa.String(), nullable=True),
        sa.Column('user_id', sa.String(length=50), nullable=True),
        sa.Column('occurred_at', sa.DateTime(), nullable=False),
        sa.Column('event_type', sa.String(length=255), nullable=True),
        sa.Column('context', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'auditlog',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('event_id', sa.UUID(), nullable=False),
        sa.Column('table_name', sa.String(), nullable=False),
        sa.Column('operation_type', sa.String(length=50), nullable=False),
        sa.Column('context', sa.JSON(), nullable=True, comment='Object contains information to query'),
        sa.Column('row_data', sa.JSON(), nullable=True, comment='Data of the row before the operation'),
        sa.Column('changed_data', sa.JSON(), nullable=True, comment='Changes from the operation'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['event_id'], ['auditevent.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )

    # Install audit
    audit_sql = read_sql_file()
    conn = op.get_bind()
    conn.execute(sa.text(audit_sql))


def read_sql_file():
    dir_path = os.path.dirname(os.path.abspath(__file__))
    file_path = os.path.join(dir_path, '01-app-audit.sql')
    with open(file_path, 'r') as file:
        return file.read()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditlog')
    op.drop_table('auditevent')
    # ### end Alembic commands ###
