"""add_project_permission_table

Revision ID: a415a915c5cc
Revises: 7d6b9d212a5f
Create Date: 2025-12-17 12:01:52.393731

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a415a915c5cc'
down_revision = '7d6b9d212a5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'projectpermission',
        sa.Column('user_id', sa.String(length=50), nullable=False),
        sa.Column('project_id', sa.String(length=50), nullable=False),
        sa.Column('permission_type', sa.String(length=10), nullable=False),
        sa.Column('granted_by_user_id', sa.String(length=50), nullable=True),
        sa.Column('id', sa.String(length=50), server_default=sa.text("gen_nanoid('pprm')"), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['granted_by_user_id'], ['user.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'project_id', name='uq_user_project_permission'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projectpermission')
    # ### end Alembic commands ###
