"""initial tables

Revision ID: ef3d7794e5b0
Revises: d71b24224f51
Create Date: 2025-12-10 11:31:51.301075

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from src.common.encrypted_field import EncryptedString

# revision identifiers, used by Alembic.
revision = 'ef3d7794e5b0'
down_revision = 'd71b24224f51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'challengetoken',
        sa.Column('jwt_id', sa.Uuid(), nullable=False),
        sa.Column('expiration_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.String(length=50), server_default=sa.text("gen_nanoid('chtk')"), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('jwt_id', 'id'),
        sa.UniqueConstraint('jwt_id'),
    )
    op.audit_table('challengetoken', True)
    op.create_table(
        'customer',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('id', sa.String(length=50), server_default=sa.text("gen_nanoid('cust')"), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'event',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('event_type', sa.String(length=100), nullable=True),
        sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('payload_class', sa.String(length=100), nullable=True),
        sa.Column('txn_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_event_event_type', 'event', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_event_type'), 'event', ['event_type'], unique=False)
    op.create_table(
        'jobstatus',
        sa.Column('job_id', sa.UUID(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('message', sa.String(), nullable=True),
        sa.Column('id', sa.String(length=50), server_default=sa.text("gen_nanoid('jstt')"), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'accesspolicy',
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('customer_id', sa.String(length=50), nullable=True),
        sa.Column(
            'permission_type', sa.String(length=50), nullable=False, comment='Permission types: READ, WRITE, ADMIN'
        ),
        sa.Column('resource_type', sa.String(length=50), nullable=False, comment='Resource types: STAFF, CUSTOMER'),
        sa.Column(
            'resource_selector',
            sa.JSON(),
            server_default='{}',
            nullable=False,
            comment='Resource selector configuration to determine which resources this permission applies to',
        ),
        sa.Column(
            'effect',
            sa.String(length=10),
            server_default='ALLOW',
            nullable=False,
            comment='Permission effect: ALLOW, DENY',
        ),
        sa.Column('id', sa.String(length=50), server_default=sa.text("gen_nanoid('apol')"), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.audit_table('accesspolicy', True)
    op.create_table(
        'accessrole',
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('customer_id', sa.String(length=50), nullable=True),
        sa.Column('is_default', sa.Boolean(), nullable=False),
        sa.Column('id', sa.String(length=50), server_default=sa.text("gen_nanoid('arol')"), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('customer_id', 'name', name='uq_access_role_name_per_customer'),
    )
    op.audit_table('accessrole', True)
    op.create_table(
        'file',
        sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('file_name', sa.String(length=1000), nullable=False),
        sa.Column('size', sa.BigInteger(), nullable=True, comment='File size in bytes'),
        sa.Column('s3_key', sa.String(length=1000), nullable=True),
        sa.Column('is_public', sa.Boolean(), nullable=False),
        sa.Column('uploaded_by_id', sa.String(length=50), nullable=True),
        sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['uploaded_by_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.audit_table('file', True)
    op.create_table(
        'membership',
        sa.Column('customer_id', sa.String(length=50), nullable=False),
        sa.Column('user_id', sa.String(length=50), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('id', sa.String(length=50), server_default=sa.text("gen_nanoid('memb')"), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('customer_id', 'user_id'),
    )
    op.audit_table('membership', True)
    op.create_table(
        'mfaauthcode',
        sa.Column('user_id', sa.String(length=50), nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('expiration_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.String(length=50), server_default=sa.text("gen_nanoid('mfac')"), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id'),
    )
    op.audit_table('mfaauthcode', True)
    op.create_table(
        'mfasecret',
        sa.Column('user_id', sa.String(length=50), nullable=False),
        sa.Column('mfa_method', sa.Enum('TOTP', 'SMS', name='mfamethodtypeenum'), nullable=False),
        sa.Column('secret', EncryptedString(), nullable=True),
        sa.Column('phone_number', sa.String(length=20), nullable=True),
        sa.Column('is_verified', sa.Boolean(), nullable=False),
        sa.Column('verification_attempts', sa.Integer(), nullable=False),
        sa.Column('backup_codes', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('verified_at', sa.DateTime(), nullable=True),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.String(length=50), server_default=sa.text("gen_nanoid('mfas')"), nullable=False),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.audit_table('mfasecret', True)
    op.create_table(
        'membershipassignment',
        sa.Column('membership_id', sa.String(length=50), nullable=False),
        sa.Column('access_role_id', sa.String(length=50), nullable=False),
        sa.Column('id', sa.String(length=50), server_default=sa.text("gen_nanoid('masgn')"), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['access_role_id'], ['accessrole.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['membership_id'], ['membership.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('membership_id', 'access_role_id', name='uq_membership_access_role'),
    )
    op.audit_table('membershipassignment', True)
    op.create_table(
        'oidcprovider',
        sa.Column('display_name', sa.String(length=100), nullable=False),
        sa.Column('discovery_endpoint', sa.String(), nullable=True),
        sa.Column('client_id', sa.String(), nullable=False),
        sa.Column('client_secret', EncryptedString(), nullable=False),
        sa.Column('client_auth_method', sa.String(length=20), nullable=False),
        sa.Column('issuer', sa.String(), nullable=True),
        sa.Column('authorization_endpoint', sa.String(), nullable=True),
        sa.Column('token_endpoint', sa.String(), nullable=True),
        sa.Column('userinfo_endpoint', sa.String(), nullable=True),
        sa.Column('jwks_uri', sa.String(), nullable=True),
        sa.Column('auto_create_users', sa.Boolean(), nullable=False),
        sa.Column('default_role_id', sa.String(length=50), nullable=True),
        sa.Column('id', sa.String(length=50), server_default=sa.text("gen_nanoid('oidc')"), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['default_role_id'], ['accessrole.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.audit_table('oidcprovider', True)
    op.create_table(
        'policyroleassignment',
        sa.Column('role_id', sa.String(length=50), nullable=False),
        sa.Column('policy_id', sa.String(length=50), nullable=False),
        sa.Column('id', sa.String(length=50), server_default=sa.text("gen_nanoid('pras')"), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['policy_id'], ['accesspolicy.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['role_id'], ['accessrole.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('policy_id', 'role_id', name='uq_policy_access_role'),
    )
    op.audit_table('policyroleassignment', True)
    op.create_table(
        'customerauthsettings',
        sa.Column('enabled_auth_methods', sa.ARRAY(sa.String()), nullable=False),
        sa.Column('mfa_methods', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('ip_whitelist', sa.ARRAY(postgresql.INET()), nullable=True),
        sa.Column('token_refresh_frequency', sa.Integer(), nullable=False),
        sa.Column('customer_id', sa.String(length=50), nullable=False),
        sa.Column('oidc_provider_id', sa.String(length=50), nullable=True),
        sa.Column('id', sa.String(length=50), server_default=sa.text("gen_nanoid('cas')"), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "\n            ('PASSWORD' = ANY(enabled_auth_methods)) OR \n            (NOT 'PASSWORD' = ANY(enabled_auth_methods) AND cardinality(mfa_methods) = 0)\n            ",
            name='password_for_2fa',
        ),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['oidc_provider_id'], ['oidcprovider.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.audit_table('customerauthsettings', True)
    op.create_table(
        'oidcprovideruser',
        sa.Column('user_id', sa.String(length=50), nullable=False),
        sa.Column('oidc_provider_id', sa.String(length=50), nullable=False),
        sa.Column('external_user_id', sa.String(), nullable=False),
        sa.Column('external_email', sa.String(), nullable=True),
        sa.Column('idp_refresh_token', EncryptedString(), nullable=True),
        sa.Column('last_idp_validation', sa.DateTime(), nullable=True),
        sa.Column('idp_user_info', sa.JSON(), nullable=True),
        sa.Column('id', sa.String(length=50), server_default=sa.text("gen_nanoid('oidp')"), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "external_user_id IS NOT NULL AND external_user_id != ''", name='external_user_id_not_empty'
        ),
        sa.ForeignKeyConstraint(['oidc_provider_id'], ['oidcprovider.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.audit_table('oidcprovideruser', True)
    op.alter_column(
        'auditlog',
        'context',
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_comment='Object contains information to query',
        existing_nullable=True,
    )
    op.create_index(
        'ix_auditlog_document_id',
        'auditlog',
        ['table_name', sa.text("(context ->> 'document_id')"), sa.text('created_at DESC')],
        unique=False,
        postgresql_where=sa.text("table_name IN ('document', 'documenttaglink')"),
    )
    op.create_index(
        'ix_auditlog_document_tag_id',
        'auditlog',
        ['table_name', sa.text("(context ->> 'document_tag_id')"), sa.text('created_at DESC')],
        unique=False,
        postgresql_where=sa.text("table_name = 'documenttag'"),
    )
    op.create_index(
        'ix_auditlog_entity_id',
        'auditlog',
        ['table_name', sa.text("(context ->> 'entity_id')"), sa.text('created_at DESC')],
        unique=False,
        postgresql_where=sa.text("table_name IN ('document', 'documenttaglink')"),
    )
    op.create_index(
        'ix_auditlog_field_lookup',
        'auditlog',
        ['table_name', sa.text("(context ->> 'field_id')"), sa.text('created_at DESC')],
        unique=False,
        postgresql_where=sa.text("table_name = 'field'"),
    )
    op.create_index(
        'ix_auditlog_field_value_lookup',
        'auditlog',
        ['table_name', sa.text("(context ->> 'field_value_id')"), sa.text('created_at DESC')],
        unique=False,
        postgresql_where=sa.text("table_name = 'fieldvalue'"),
    )
    op.create_index(
        'ix_auditlog_fieldvalue_id',
        'auditlog',
        [sa.text("(context ->> 'field_value_id')"), 'created_at', 'event_id'],
        unique=False,
        postgresql_where=sa.text("table_name = 'fieldvalue'"),
    )
    op.create_index('ix_auditlog_table_name', 'auditlog', ['table_name'], unique=False)
    op.create_index(
        'ix_auditlog_temporal_model_entity',
        'auditlog',
        [
            'table_name',
            sa.text("(context ->> 'is_temporal')"),
            sa.text("(context ->> 'model_id')"),
            sa.text("(context ->> 'entity_id')"),
            sa.text('created_at DESC'),
        ],
        unique=False,
        postgresql_where=sa.text("table_name = 'fieldvalue'"),
    )
    op.create_index(
        'ix_auditlog_temporal_model_namespace',
        'auditlog',
        [
            'table_name',
            sa.text("(context ->> 'is_temporal')"),
            sa.text("(context ->> 'model_id')"),
            sa.text("(context ->> 'namespace_id')"),
            sa.text('created_at DESC'),
        ],
        unique=False,
        postgresql_where=sa.text("table_name = 'field'"),
    )
    op.add_column('user', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('user', sa.Column('archived_at', sa.Date(), nullable=True))
    op.create_index(
        'idx_search_user_email',
        'user',
        [sa.text("to_tsvector('english', 'email')")],
        unique=False,
        postgresql_using='gin',
    )
    op.create_index(
        'idx_search_user_email_simple',
        'user',
        [sa.text("to_tsvector('simple', 'email')")],
        unique=False,
        postgresql_using='gin',
    )
    op.create_index(
        'idx_search_user_name',
        'user',
        [sa.text("to_tsvector('english', COALESCE(first_name, '') || ' ' || COALESCE(last_name, ''))")],
        unique=False,
        postgresql_using='gin',
    )
    op.create_index(
        'idx_search_user_name_simple',
        'user',
        [sa.text("to_tsvector('simple', COALESCE(first_name, '') || ' ' || COALESCE(last_name, ''))")],
        unique=False,
        postgresql_using='gin',
    )
    op.create_index('idx_user_email_lower', 'user', [sa.text('lower(email)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_email_lower', table_name='user')
    op.drop_index('idx_search_user_name_simple', table_name='user', postgresql_using='gin')
    op.drop_index('idx_search_user_name', table_name='user', postgresql_using='gin')
    op.drop_index('idx_search_user_email_simple', table_name='user', postgresql_using='gin')
    op.drop_index('idx_search_user_email', table_name='user', postgresql_using='gin')
    op.drop_column('user', 'archived_at')
    op.drop_column('user', 'hashed_password')
    op.drop_index(
        'ix_auditlog_temporal_model_namespace', table_name='auditlog', postgresql_where=sa.text("table_name = 'field'")
    )
    op.drop_index(
        'ix_auditlog_temporal_model_entity',
        table_name='auditlog',
        postgresql_where=sa.text("table_name = 'fieldvalue'"),
    )
    op.drop_index('ix_auditlog_table_name', table_name='auditlog')
    op.drop_index(
        'ix_auditlog_fieldvalue_id', table_name='auditlog', postgresql_where=sa.text("table_name = 'fieldvalue'")
    )
    op.drop_index(
        'ix_auditlog_field_value_lookup', table_name='auditlog', postgresql_where=sa.text("table_name = 'fieldvalue'")
    )
    op.drop_index('ix_auditlog_field_lookup', table_name='auditlog', postgresql_where=sa.text("table_name = 'field'"))
    op.drop_index(
        'ix_auditlog_entity_id',
        table_name='auditlog',
        postgresql_where=sa.text("table_name IN ('document', 'documenttaglink')"),
    )
    op.drop_index(
        'ix_auditlog_document_tag_id', table_name='auditlog', postgresql_where=sa.text("table_name = 'documenttag'")
    )
    op.drop_index(
        'ix_auditlog_document_id',
        table_name='auditlog',
        postgresql_where=sa.text("table_name IN ('document', 'documenttaglink')"),
    )
    op.alter_column(
        'auditlog',
        'context',
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_comment='Object contains information to query',
        existing_nullable=True,
    )
    op.audit_table('oidcprovideruser', False)
    op.drop_table('oidcprovideruser')
    op.audit_table('customerauthsettings', False)
    op.drop_table('customerauthsettings')
    op.audit_table('policyroleassignment', False)
    op.drop_table('policyroleassignment')
    op.audit_table('oidcprovider', False)
    op.drop_table('oidcprovider')
    op.audit_table('membershipassignment', False)
    op.drop_table('membershipassignment')
    op.audit_table('mfasecret', False)
    op.drop_table('mfasecret')
    op.audit_table('mfaauthcode', False)
    op.drop_table('mfaauthcode')
    op.audit_table('membership', False)
    op.drop_table('membership')
    op.audit_table('file', False)
    op.drop_table('file')
    op.audit_table('accessrole', False)
    op.drop_table('accessrole')
    op.audit_table('accesspolicy', False)
    op.drop_table('accesspolicy')
    op.drop_table('jobstatus')
    op.drop_index(op.f('ix_event_event_type'), table_name='event')
    op.drop_index('idx_event_event_type', table_name='event')
    op.drop_table('event')
    op.drop_table('customer')
    op.audit_table('challengetoken', False)
    op.drop_table('challengetoken')
    # ### end Alembic commands ###
