"""Add color to project and description to task

Revision ID: d3da8826f088
Revises: dc72e795a482
Create Date: 2025-12-14 18:14:54.401164

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd3da8826f088'
down_revision = 'dc72e795a482'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('color', sa.String(), nullable=True))
    op.add_column('task', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'description')
    op.drop_column('project', 'color')
    # ### end Alembic commands ###
