"""Add projects, sections, and tasks tables

Revision ID: dc72e795a482
Revises: a7bc1b588c07
Create Date: 2025-12-14 18:11:09.718551

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc72e795a482'
down_revision = 'a7bc1b588c07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'project',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('id', sa.String(length=50), server_default=sa.text("gen_nanoid('proj')"), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'section',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('project_id', sa.String(length=50), nullable=False),
        sa.Column('display_order', sa.Integer(), nullable=False),
        sa.Column('is_expanded', sa.Boolean(), nullable=False),
        sa.Column('id', sa.String(length=50), server_default=sa.text("gen_nanoid('sect')"), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['project_id'],
            ['project.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'task',
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('project_id', sa.String(length=50), nullable=False),
        sa.Column('section_id', sa.String(length=50), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('display_order', sa.Integer(), nullable=False),
        sa.Column('id', sa.String(length=50), server_default=sa.text("gen_nanoid('task')"), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['project_id'],
            ['project.id'],
        ),
        sa.ForeignKeyConstraint(
            ['section_id'],
            ['section.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.alter_column(
        'accesspolicy',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'accessrole',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'auditevent',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'auditlog',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'challengetoken',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'customer',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'customerauthsettings',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'event',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'file',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'jobstatus',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'membership',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'membershipassignment',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'mfaauthcode',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'oidcprovider',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'oidcprovideruser',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'permission',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'policyroleassignment',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column('todo', 'completed', existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        'todo',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'user',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'todo',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column('todo', 'completed', existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        'policyroleassignment',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'permission',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'oidcprovideruser',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'oidcprovider',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'mfaauthcode',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'membershipassignment',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'membership',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'jobstatus',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'file',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'event',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'customerauthsettings',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'customer',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'challengetoken',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'auditlog',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'auditevent',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'accessrole',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'accesspolicy',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.drop_table('task')
    op.drop_table('section')
    op.drop_table('project')
    # ### end Alembic commands ###
