"""add_invitation_table

Revision ID: 9af58768563c
Revises: a415a915c5cc
Create Date: 2025-12-17 12:04:21.675727

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9af58768563c'
down_revision = 'a415a915c5cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'invitation',
        sa.Column('email', sa.String(length=320), nullable=False),
        sa.Column('customer_id', sa.String(length=50), nullable=False),
        sa.Column('invited_by_user_id', sa.String(length=50), nullable=False),
        sa.Column('token', sa.String(length=128), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('project_permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('message', sa.String(length=1000), nullable=True),
        sa.Column('accepted_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.String(length=50), server_default=sa.text("gen_nanoid('invt')"), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['invited_by_user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_invitation_email'), 'invitation', ['email'], unique=False)
    op.create_index(
        'ix_invitation_email_customer_status', 'invitation', ['email', 'customer_id', 'status'], unique=False
    )
    op.create_index(op.f('ix_invitation_token'), 'invitation', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitation_token'), table_name='invitation')
    op.drop_index('ix_invitation_email_customer_status', table_name='invitation')
    op.drop_index(op.f('ix_invitation_email'), table_name='invitation')
    op.drop_table('invitation')
    # ### end Alembic commands ###
